### ISSUE TITLE
Scene Caching Tries to Access the Wrong File in Certain Circumstances

### ISSUE THREAD

**Issue by sudgy** [ManimCommunity/manim#451]
Consider the following scene:

```python
class Issue3DCache(ThreeDScene):
    def construct(self):
        self.begin_ambient_camera_rotation(rate=0.1)
        self.wait()
        self.wait()
```

when I run manim once, it makes a black screen as expected, but when I run it again, it crashes saying that it can't find the partial movie file.

When running `manim test.py Issue3DCache -pl` the first time:
```
Animation 0 : Partial movie file written in {'.../480p15/partial_movie_files/Issue3DCache/2314591449_1-0_2415171488.mp4'}
Animation 1 : Partial movie file written in {'.../480p15/partial_movie_files/Issue3DCache/1347326907_1-0_2415171488.mp4'}
```
When running it again:
```
Wait 0 : Using cached data (hash : 2314591449_1-0_2415171488)
Animation 1 : Partial movie file written in {'.../480p15/partial_movie_files/Issue3DCache/2314591449_1-0_2415171488.mp4'}
Impossible to open 'file:.../480p15/partial_movie_files/Issue3DCache/865043704_1-0_2415171488.mp4'
.../480p15/partial_movie_files/Issue3DCache/partial_movie_file_list.txt: No such file or directory
```

**Comment by huguesdevimeux** [comment]
Hi, thanks for the report. Did you try to run this with `--disable_caching` flag ?

**Comment by sudgy** [comment]
Yeah, I did, and it works fine when using that flag.

**Comment by sudgy** [comment]
Well, I just found somewhere else it breaks without rotation.  Let me try to isolate what's breaking it.

**Comment by sudgy** [comment]
Here's a reduced case of another case I found:
```python
class Issue3DCache2(Scene):
    def construct(self):
        self.wait()
        m = Square()
        self.add(m)
        #self.wait()
```
Run it the first time without the commented wait, and the second time with it.  Then a similar problem occurs.  However, unlike before, the wait has to be added between runs.

**Comment by huguesdevimeux** [comment]
Alright, thanks so much for that. 
Last request (I swear !) Could you run a borken scene with `-v DEBUG` flag (and **without** `--disable_caching` flag)and post the logs ?

**Comment by sudgy** [comment]
[output.txt](https://github.com/ManimCommunity/manim/files/5246616/output.txt)

This was the second one (without the rotation), even though the name is still `Issue3DCache`.  It doesn't seem to be that much different.

**Comment by sudgy** [comment]
I was wanting to jump to an earlier commit so I wouldn't have to deal with this problem any more, and I found that the bug was introduced in commit 1a516db.

**Comment by huguesdevimeux** [comment]
Maybe this is fixed by #489 . I tested it, and it worked. Could you confirm ?

**Comment by sudgy** [comment]
If it worked for you, I'm fine trusting that.  I don't really know any way to test it right now short of uninstalling my copy and then installing from your fork, and that seems like more trouble than it's worth.

**Comment by sudgy** [comment]
This has been closed, but it's not actually fixed yet.  I'm guessing somebody got confused and thought that #489 was #498.

**Comment by huguesdevimeux** [comment]
Sorry for that. nevertheless, now everything is good as #489 is merged :D
